"""Constants for Lighing Zone."""

import voluptuous as vol
from homeassistant.components.light import (
    ATTR_BRIGHTNESS,
    ATTR_BRIGHTNESS_PCT,
    ATTR_BRIGHTNESS_STEP,
    ATTR_BRIGHTNESS_STEP_PCT,
    VALID_BRIGHTNESS,
    VALID_BRIGHTNESS_PCT,
    VALID_BRIGHTNESS_STEP,
    VALID_BRIGHTNESS_STEP_PCT,
)
from homeassistant.const import Platform

DOMAIN = "lighting_zone"

PLATFORMS = [Platform.BINARY_SENSOR]

CONF_MEMBERS = "members"

SERVICE_DIM_ZONE_ABSOLUTE = "dim_zone_absolute"
SERVICE_DIM_ZONE_ABSOLUTE_SCHEMA = {
    vol.Exclusive(ATTR_BRIGHTNESS, ATTR_BRIGHTNESS): VALID_BRIGHTNESS,
    vol.Exclusive(ATTR_BRIGHTNESS_PCT, ATTR_BRIGHTNESS): VALID_BRIGHTNESS_PCT,
}

SERVICE_DIM_ZONE_RELATIVE = "dim_zone_relative"
SERVICE_DIM_ZONE_RELATIVE_SCHEMA = {
    vol.Exclusive(ATTR_BRIGHTNESS_STEP, ATTR_BRIGHTNESS_STEP): VALID_BRIGHTNESS_STEP,
    vol.Exclusive(
        ATTR_BRIGHTNESS_STEP_PCT, ATTR_BRIGHTNESS_STEP
    ): VALID_BRIGHTNESS_STEP_PCT,
}
