dim_zone_absolute:
    target:
        entity:
            domain: binary_sensor
            integration: lighting_zone
    fields:
        brightness:
            default: 50
            selector:
                number:
                    min: 0
                    max: 255
        brightness_pct:
            selector:
                number:
                    min: 0
                    max: 100

dim_zone_relative:
    target:
        entity:
            domain: binary_sensor
            integration: lighting_zone
    fields:
        brightness_step:
            default: -50
            selector:
                number:
                    min: -255
                    max: 255
        brightness_step_pct:
            selector:
                number:
                    min: -100
                    max: 100

reload: